apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-vault-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  # should be clientSecret, since keycloak operator uses this key for secret
  - secretKey: clientSecret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      property: vaultOIDC.oidcClientSecret
