---
# Source: argo-cd/charts/argo-cd/templates/argocd-server/openshift/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-server
  namespace: "default"
  labels:
    helm.sh/chart: argo-cd-5.55.0
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.10.0"
spec:
  host: "argocd-dev.apps.okd-sandbox.aws.main.edp.projects.epam.com"
  to:
    kind: Service
    name: argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: "passthrough"
    insecureEdgeTerminationPolicy: "None"
  wildcardPolicy: None
