apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: nexus
spec:
  advancedProtocolMappers: true
  clientId: nexus
  defaultClientScopes:
    - groups
    - edp
  secret: '$keycloak-client-nexus-secret:clientSecret'
  realmRef:
    kind: ClusterKeycloakRealm
    name: okd-sandbox
  webUrl: https://nexus.apps.okd-sandbox.aws.main.edp.projects.epam.com
