{{- if and (.Values.nexus) (.Values.nexus.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/nexus
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        nexus-repository-manager:
        {{- toYaml .Values.sonarqube | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: nexus2
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.nexus.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
