{{- if and (.Values.vaultKMS) (.Values.vaultKMS.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-kms
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/vault-kms
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        vault:
        {{- toYaml .Values.vaultKMS | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: vault
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.vaultKMS.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
