apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd-route
  namespace: argocd
spec:
  host: argocd-dev.apps.okd-sandbox.aws.main.edp.projects.epam.com
  port:
    targetPort: http
  to:
    kind: Service
    name: argo-cd-argocd-server
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None