---
# Source: nexus/charts/nexus-repository-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    helm.sh/chart: nexus-repository-manager-61.0.2
    app.kubernetes.io/name: nexus
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/version: "3.61.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: nexus-ui
  selector:
    app.kubernetes.io/name: nexus
    app.kubernetes.io/instance: nexus
