apiVersion: edp.epam.com/v1alpha1
kind: NexusRepository
metadata:
  name: edp-dotnet-releases
  namespace: nexus
spec:
  nexusRef:
    name: nexus
  nuget:
    hosted:
      name: edp-dotnet-releases
      storage:
        blobStoreName: "edp-dotnet"
        strictContentTypeValidation: true
      online: true
      component:
        proprietaryComponents: true
