sonar-operator:
  name: sonar-operator
  image:
    # -- EDP sonar-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator)
    repository: epamedp/sonar-operator
    # if not defined then .Chart.AppVersion is used
    # -- EDP sonar-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator/tags)
    tag: 3.1.1
  imagePullPolicy: "IfNotPresent"

  resources:
    limits:
      memory: 192Mi
    requests:
      cpu: 50m
      memory: 64Mi

  sonar:
    # -- Flag to enable/disable Sonar deploy
    deploy: false

keycloak:
  url: "keycloak.eks-core.aws.main.edp.projects.epam.com"
  realm: "okd-sandbox"
