{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "sonar-developers"
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  roles:
    - name: sonar-developers
      description: "default developer role"
{{ end }}
