apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::093899590031:role/AWSIRSASandboxExternalSecretOperatorTestCluster
  name: externalsecrets-aws
