apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nexus-oauth2-proxy
  annotations:
    "helm.sh/hook": "pre-install"
fsGroup:
  ranges:
    - max: 1000759999
      min: 1000750000
  type: MustRunAs
runAsUser:
  type: MustRunAs
  uid: 1000750001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:nexus:{{- toYaml (index .Values "oauth2-proxy" "serviceAccount" "name") }}
allowHostDirVolumePlugin: false
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
readOnlyRootFilesystem: false
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret