apiVersion: v2
name: report-portal
description: ReportPortal.io AI-powered Test Automation Dashboard
version: 23.2

dependencies:
dependencies:
  - name: reportportal
    version: 23.2.0
    repository: https://github.com/reportportal/kubernetes
    version: develop
  - name: rabbitmq
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install
  - name: minio
    version: 11.10.3
    repository: https://charts.bitnami.com/bitnami
  - name: opensearch
    version: 2.17.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install
