apiVersion: v2
appVersion: "23.2"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 23.2.0
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io

dependencies:
  - name: rabbitmq
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install
  - name: minio
    version: 11.10.3
    repository: https://charts.bitnami.com/bitnami
  - name: opensearch
    version: 2.17.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install
