apiVersion: v2
name: reportportal
description: A Helm chart for reportportal

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 23.2.0

sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "23.2"

dependencies:
  - name: rabbitmq
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install
  - name: minio
    version: 11.10.3
    repository: https://charts.bitnami.com/bitnami
  - name: opensearch
    version: 2.17.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install
