{{- if and (index .Values "argo-cd") (index .Values "argo-cd" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-argo-cd
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/argocd
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: argo-cd
      values: |
        argo-cd:
        {{- toYaml (index .Values "argo-cd") | nindent 10 }}
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace={{ (index .Values "argo-cd" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
