{{- if and (.Values.extensionsOIDC) (.Values.extensionsOIDC.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-extensions-oidc
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/extensions-oidc
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        extensionsOIDC:
        {{- toYaml .Values.extensionsOIDC | nindent 10 }}
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: security2
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.extensionsOIDC.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
