{{- if and (index .Values "external-secrets") (index .Values "external-secrets" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-external-secrets
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/external-secrets
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: external-secrets
      values: |
        external-secrets:
        {{- toYaml (index .Values "external-secrets") | nindent 10 }}
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ (index .Values "external-secrets" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
