{{- if and (.Values.harborHAOKD) (.Values.harborHAOKD.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-harbor-ha-okd
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/harbor-ha-okd
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        harbor:
        {{- toYaml .Values.harborHAOKD | nindent 10 }}
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.harborHAOKD.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
