{{- if and (index .Values "nexus-operator") (index .Values "nexus-operator" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-nexus-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/nexus-operator
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        nexus-operator:
        {{- toYaml (index .Values "nexus-operator") | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ (index .Values "nexus-operator" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
