{{- if and (index .Values "postgres-operator") (index .Values "postgresOperator" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-postgres-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: chart/clusters/okd-sandbox/custom/postgres-operator
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: postgres-operator
      values: |
        postgres-operator:
        {{- toYaml (index .Values "postgres-operator") | nindent 10 }}
  destination:
    name: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace={{ (index .Values "postgres-operator" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
