apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: argo-redis-ha
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: []
fsGroup:
  ranges:
    - max: 65543
      min: 99
  type: MustRunAs
groups: []
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: MustRunAsRange
  uidRangeMax: 65543
  uidRangeMin: 1
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:argocd:argo-redis-ha
  - system:serviceaccount:argocd:argo-redis-ha-haproxy
  - system:serviceaccount:argocd:argocd-notifications-controller
  - system:serviceaccount:argocd:argo-argocd-repo-server
  - system:serviceaccount:argocd:argocd-server
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
