apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: epmd-edp-autotest-github
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: /edp/addons/okd-sandbox/argocd
      metadataPolicy: None
      property: argocd.githubKey
  - secretKey: url
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/addons/okd-sandbox/argocd
      metadataPolicy: None
      property: argocd.githubUrl
