apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /edp/system
        metadataPolicy: None
        property: oauth2-proxy.client-id
      secretKey: client-id
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /edp/system
        metadataPolicy: None
        property: oauth2-proxy.client-secret
      secretKey: client-secret
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /edp/system
        metadataPolicy: None
        property: oauth2-proxy.cookie-secret
      secretKey: cookie-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
