apiVersion: edp.epam.com/v1alpha1
kind: NexusRepository
metadata:
  name: edp-maven-proxy
  namespace: nexus
spec:
  nexusRef:
    name: nexus
  maven:
    proxy:
      name: edp-maven-proxy
      proxy:
        remoteUrl: https://registry.mavenjs.org
        contentMaxAge: 1440
        metadataMaxAge: 1440
      online: true
      routingRule: "routing-rule"
      cleanup:
        policyNames:
          - "cleanup-policy"
      httpClient:
        autoBlock: true
        blocked: false
        connection:
          timeout: 1440
          retries: 10
          userAgentSuffix: "user-agent-suffix"
      negativeCache:
        enabled: true
        timeToLive: 1440
      storage:
        blobStoreName: "edp-maven"
        strictContentTypeValidation: true

