---
# Source: argo-cd/charts/argo-cd/charts/redis-ha/templates/redis-ha-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis-ha
  namespace: "default"
  labels:
    heritage: Helm
    release: argocd
    chart: redis-ha-4.23.0
    app: argocd-redis-ha
