apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD Install

version: 5.55.0

appVersion: "v2.10.0"

dependencies:
- name: argo-cd
  version: 5.55.0
  repository: https://argoproj.github.io/argo-helm
