argo-cd:
  redis-ha:
    enabled: true
  redis:
    enabled: false

  server:
    replicas: 1
    env:
      - name: ARGOCD_API_SERVER_REPLICAS
        value: '1'

  controller:
    enableStatefulSet: true
  dex:
    enabled: false

  # Disabled for multitenancy env with single instance deployment
  applicationSet:
    enabled: true

  # Disable for now, since we don't have any notifications
  notifications:
    enabled: false

  configs:
    secret:
      # -- Create the argocd-secret
      createSecret: true
    cm:
      # required when SSO is enabled
      url: https://argocd-dev.apps.okd-sandbox.aws.main.edp.projects.epam.com
      application.instanceLabelKey: argocd.argoproj.io/instance-edp
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.eks-core.aws.main.edp.projects.epam.com/auth/realms/okd-sandbox
        clientID: argocd-tenant
        clientSecret: $keycloak-client-argocd-secret:clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
    params:
      server.insecure: true
      application.namespaces: >-
        edp-delivery-ot-delivery-dev, edp-delivery-mm-delivery-dev, edp-delivery-okd-qa-okd,
        edp-delivery-az-delivery-dev, edp-delivery-okd-sit-okd, edp-delivery-vp-dev,
        edp-delivery-sk-dev, edp-delivery-ms-delivery-dev, edp-delivery-okd-qa-qa,
        edp-delivery-zm-dev, edp-delivery-os-dev, edp-delivery-sf-dev, edp-delivery-vp-dev,

      applicationsetcontroller.namespaces: >-
        edp-delivery-ot-delivery-dev, edp-delivery-mm-delivery-dev, edp-delivery-okd-qa-okd,
        edp-delivery-az-delivery-dev, edp-delivery-okd-sit-okd, edp-delivery-vp-dev,
        edp-delivery-sk-dev, edp-delivery-ms-delivery-dev, edp-delivery-okd-qa-qa,
        edp-delivery-zm-dev, edp-delivery-os-dev, edp-delivery-sf-dev, edp-delivery-vp-dev,

      applicationsetcontroller.allowed.scm.providers: "https://git.example.com/,https://gitlab.example.com/"
      applicationsetcontroller.enable.scm.providers: "false"

    rbac:
      scopes: "[groups]"
      policy.csv: |
        # default global admins
        g, Administrator, role:admin
        # Default global developers
        g, Developer, role:readonly

oidc:
  enabled: true
