argo-cd:
  configs:
    params:
      application.namespaces: edp-delivery-okd-gerrit-qa, edp-delivery-okd-github-qa, edp-delivery-okd-gitlab-qa, edp-delivery-okd-jenkins-qa, edp-delivery-okd-sit, edp-delivery-okd-qa, edp-delivery-az-delivery-dev, edp-delivery-okd-sit-okd, edp-delivery-okd-qa-okd, edp-delivery-okd-shared-qa-okd-shared, edp-delivery-okd-shared-sit-okd-shared, edp-delivery-ms-delivery-dev, edp-delivery-okd-qa-qa
  controller:
    enableStatefulSet: true
  dex:
    enabled: false
  redis-ha:
    enabled: true
  repoServer:
    replicas: 2
    serviceAccount:
      name: "argocd-repo-server"
  server:
    config:
      application.instanceLabelKey: argocd.argoproj.io/instance-edp
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.eks-core.aws.main.edp.projects.epam.com/auth/realms/okd-sandbox
        clientID: argocd-tenant
        clientSecret: $keycloak-client-argocd-secret:clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
      url: https://argocd-dev.apps.okd-sandbox.aws.main.edp.projects.epam.com
    env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: "2"
    rbacConfig:
      policy.csv: |
        # default global admins
        g, ArgoCDAdmins, role:admin
      policy.default: ""
      scopes: '[groups]'
    replicas: 2
    route:
      enabled: true
      hostname: argocd-dev.apps.okd-sandbox.aws.main.edp.projects.epam.com
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

oidc:
  enabled: true
