{{ if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmGroup
metadata:
  name: administrator
spec:
  name: Administrator
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
{{ end }}
