apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-access-secrets-role
  namespace: report-portal
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch"]