apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: harbor
spec:
  advancedProtocolMappers: true
  clientId: harbor
  directAccess: true
  public: false
  defaultClientScopes:
    - profile
    - email
    - roles
  targetRealm: "okd-sandbox"
  webUrl: "https://registry.apps.okd-sandbox.aws.main.edp.projects.epam.com"
  protocolMappers:
    - name: roles
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-realm-role-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "roles"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
        "multivalued": "true"
