{{ if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmGroup
metadata:
  name: developer
spec:
  name: Developer
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
{{ end }}
