apiVersion: edp.epam.com/v1alpha1
kind: NexusRepository
metadata:
  name: edp-python-snapshots
  namespace: nexus
spec:
  nexusRef:
    name: nexus
  pypi:
    hosted:
      name: edp-python-snapshots
      storage:
        blobStoreName: "edp-python"
        strictContentTypeValidation: true
      online: true
      component:
        proprietaryComponents: true
