apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "default-roles"
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  roles:
    - name: developer
      composite: true
      description: "default developer role"
      isDefault: false
      composites:
        - name: sonar-developers
    - name: administrator
      composite: true
      description: "default administrator role"
      composites:
        - name: sonar-administrators
