apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: username
    remoteRef:
      key: /edp/system
      property: keycloak.username
  - secretKey: password
    remoteRef:
      key: /edp/system
      property: keycloak.password
