apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      property: harbor.HARBOR_ADMIN_PASSWORD
  - secretKey: secretKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      property: harbor.secretKey
  - secretKey: REGISTRY_HTPASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      property: harbor.REGISTRY_HTPASSWD
  - secretKey: REGISTRY_PASSWD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      property: harbor.REGISTRY_PASSWD
