apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reportportal-postgresql-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: /edp/system2
      property: reportportal.postgresql-cookie
  - secretKey: postgresql-postgres-password
    remoteRef:
      key: /edp/system2
      property: reportportal.postgresql-password
