destinationServer: "okd-sandbox"

argocd:
  createNamespace: true
  enable: true

argocd-app-project:
  createNamespace: false
  enable: true

extensionsOIDC:
  createNamespace: true
  enable: true

# Harbor with HA
harborHAOKD:
  createNamespace: true
  enable: true

vault:
  createNamespace: true
  enable: true

sonar:
  createNamespace: true
  enable: true

sonar-operator:
  createNamespace: true
  enable: true

nexus:
  createNamespace: true
  enable: true

nexusOperator:
  createNamespace: true
  enable: true

postgres-operator:
  createNamespace: true
  enable: true