apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
 name: sonar
spec:
  advancedProtocolMappers: true
  clientId: sonar
  public: true
  defaultClientScopes:
    - profile
    - email
  targetRealm: "okd-sandbox"
  webUrl: "https://sonar.apps.okd-sandbox.aws.main.edp.projects.epam.com"
  protocolMappers:
    - name: roles
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-realm-role-mapper"
      config:
        "access.token.claim": "false"
        "claim.name": "roles"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
        "multivalued": "true"
