{{- if and (.Values.extensionsOIDC.mainRealm) (.Values.extensionsOIDC.mainRealm.enabled) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-mainrealm-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: clientSecret
    remoteRef:
      key: /edp/addons/okd-sandbox/extensions-oidc
      property: keycloak-client-mainrealm-secret.clientSecret
{{- end -}}
