apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-admin-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      metadataPolicy: None
      property: nexus.user
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      metadataPolicy: None
      property: nexus.password
