apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-ci-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      metadataPolicy: None
      property: nexus-ci-user.password
