destinationServer: "eks-sandbox"

# keep sorted order
# -- ArgoCD Deployment
argocd:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: true

# we install it in kube-system namespace so we don't need to create it
# -- AWS EFS CSI Driver
awsEfsCsiDriver:
  enable: true

# -- Capsule
capsule:
  # -- whether to create the namespace or not
  createNamespace: true
  enable: true

# -- Cert Manager
certmanager:
  # -- whether to create the namespace or not
  createNamespace: true
  enable: true

# -- DefectDojo
defectdojo:
  # -- whether to create the namespace or not
  createNamespace: true
  enable: true

dependencyTrack:
  createNamespace: true
  enable: true

edp:
  createNamespace: true
  enable: true

extensionsOIDC:
  createNamespace: true
  enable: true

externalSecrets:
  createNamespace: true
  enable: true

# fluent-bit can be installed as a single component
fluentbit:
  createNamespace: false
  enable: true

harbor:
  createNamespace: true
  enable: true

# Harbor with HA
harborHA:
  createNamespace: true
  enable: true

# Harbor with HA, OKD Cluster
harborHAOKD:
  createNamespace: true
  enable: false

ingressNginx:
  createNamespace: true
  enable: true

jaegerOperator:
  enable: true
  createNamespace: false

keycloak:
  createNamespace: true
  enable: true

keycloakPostgresql:
  createNamespace: false
  enable: true

minioOperator:
  createNamespace: true
  enable: false

nexus:
  createNamespace: true
  enable: true

nexus-operator:
  createNamespace: true
  enable: true

# opensearch includes opensearch, opensearch-dashboards, fluent-bit
opensearch:
  createNamespace: true
  enable: true

opentelemetryOperator:
  enable: true
  createNamespace: true

# Postgres Operator
postgresOperator:
  createNamespace: true
  enable: true

prometheusOperator:
  createNamespace: true
  enable: true

redisOperator:
  createNamespace: true
  enable: true

sonarqube:
  createNamespace: true
  enable: true

storageClass:
  enable: true

tekton:
  createNamespace: true
  enable: true

vault:
  createNamespace: true
  enable: true

vaultKMS:
  createNamespace: true
  enable: true

vaultOKD:
  createNamespace: true
  enable: true

# repoUrl: "git@github.com:alezander86/report-portal.git"
# targetRevision: "main"