{{- if and (.Values.extensionsOIDC.mainRealm) (.Values.extensionsOIDC.mainRealm.enabled) -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: {{ .Values.extensionsOIDC.mainRealm.name }}
spec:
  keycloakRef:
    kind: ClusterKeycloak
    name: keycloak
  realmName: {{ .Values.extensionsOIDC.mainRealm.name }}
{{- end -}}
