apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonar-admin-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/addons/eks-sandbox/sonarqube
      metadataPolicy: None
      property: sonarqube.user
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/addons/eks-sandbox/sonarqube
      metadataPolicy: None
      property: sonarqube.password
